language: elixir
elixir: 1.4.2
otp_release: 19.3
sudo: false
matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.0
    - elixir: 1.4.5
      otp_release: 19.3
    - elixir: 1.5.2
      otp_release: 20.0
    - elixir: 1.6.0
      otp_release: 20.0
