version: appveyor-{build}

environment:
 elixir_version: 1.6.0

install:
  - cinst elixir --version %elixir_version%
  - refreshenv

build_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test_script:
  mix test
