version: appveyor-{build}

environment:
  matrix:
    - elixir_version: 1.10.3
    - elixir_version: 1.11.4
    - elixir_version: 1.12.3
    - elixir_version: 1.13.2

install:
  - cinst elixir --version %elixir_version%
  - refreshenv

build_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test_script:
  - mix test
