version: appveyor-{build}

environment:
  matrix:
    - elixir_version: 1.4.2
    - elixir_version: 1.3.4

install:
  - cinst elixir --version %elixir_version%
  - refreshenv

build_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

test_script:
  mix test
